// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx9FhaZulBkNpbDr79K3WATwWAfQ6fjkM',
    appId: '1:659535326641:android:5214d4cc2a6c9dfdc36190',
    messagingSenderId: '659535326641',
    projectId: 'izmafood-6c1a2',
    storageBucket: 'izmafood-6c1a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANQr1YFGql2NVFa4giLJkRYMmlK96pyVE',
    appId: '1:659535326641:ios:125ee3bad6b25ea6c36190',
    messagingSenderId: '659535326641',
    projectId: 'izmafood-6c1a2',
    storageBucket: 'izmafood-6c1a2.firebasestorage.app',
    androidClientId: '659535326641-j95qadv7iu5usschnfaj3c7h1pg67sm3.apps.googleusercontent.com',
    iosClientId: '659535326641-aka7ee0liecg432l25qei728fvp07gpn.apps.googleusercontent.com',
    iosBundleId: 'com.example.izmaFoodsVendor',
  );
}
